<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="c7a5d765-8d2c-46c6-b13a-61ac8fb4f7c0" name="Admin@D46 2022-03-17 09:49:09" runUser="D46\Admin" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="904e1636-c7f5-45e3-b84f-b9dab1cc98be">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Admin_D46 2022-03-17 09_49_09">
      <DeploymentItem filename="D:\KTPM\Calculator\Calculator\Calculator\bin\Debug\Calculator.exe" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2022-03-17T09:49:09.4130000+07:00" queuing="2022-03-17T09:49:09.4300000+07:00" start="2022-03-17T09:49:09.4330000+07:00" finish="2022-03-17T09:49:09.5620000+07:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TestPolynomial2" storage="d:\ktpm\calculator\calculator\calculatortester\bin\debug\calculatortester.dll" id="de38e6c8-8158-9263-cea4-ceb1904356d5">
      <Execution id="aab291c7-193d-4839-badb-48a18fa0cd06" />
      <TestMethod codeBase="D:/KTPM/Calculator/Calculator/CalculatorTester/bin/Debug/CalculatorTester.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="CalculatorTester.Cau2, CalculatorTester, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TestPolynomial2" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="de38e6c8-8158-9263-cea4-ceb1904356d5" executionId="aab291c7-193d-4839-badb-48a18fa0cd06" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="aab291c7-193d-4839-badb-48a18fa0cd06" testId="de38e6c8-8158-9263-cea4-ceb1904356d5" testName="TestPolynomial2" computerName="D46" duration="00:00:00.0117414" startTime="2022-03-17T09:49:09.4370000+07:00" endTime="2022-03-17T09:49:09.5500000+07:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="aab291c7-193d-4839-badb-48a18fa0cd06">
      <Output>
        <ErrorInfo>
          <Message>Test method CalculatorTester.Cau2.TestPolynomial2 did not throw expected exception System.ArgumentException.</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>